### PR TITLE
Create new fireline collections

### PR DESCRIPTION
**Pull request by smohiudd**
New collections for vector fireline datasets:

- fireline
- newfirepix
- perimeter

### CODE REVIEW

**Comment by mccabete** [comment]
Hello @smohiudd, I just did a PR into this branch with my changes. 

Are there other places I could include more documentation? Ideally, there would be places for me to reference the underlying algorithm that generated this stuff, and a place for me to include descriptions of all the feature properties (like we do in the documentation [here](https://nasa-impact.github.io/veda-docs/example-notebooks/wfs.html). Maybe an information link like they do for the [pygeo api](https://demo.pygeoapi.io/master/collections/lakes)?

**Comment by smohiudd** [comment]
@mccabete I merged your commits from the other branch. Beside the discussion on data properties descriptions, did you have any thoughts on including links to publications, methodology, etc.? If you're still working on that, I can deploy the STAC collection as is and we can add to it at a later time.

**Comment by mccabete** [comment]
Hey @smohiudd, 

Yep! I'd love to add some stuff per your suggestions! Feel free to deploy in the meantime, because I may/may not get to it today.

**Comment by smohiudd** [comment]
@mccabete for the scientific extension, all you need to add `sci: ***` properties as well add:  
```
 "stac_extensions": [
    "https://stac-extensions.github.io/scientific/v1.0.0/schema.json"
  ]
```
Here is an example: https://github.com/stac-extensions/scientific/blob/main/examples/collection.json

**Comment by gadomski** [comment]
This repo is being sunsetted (https://github.com/NASA-IMPACT/veda-data-pipelines/pull/360), so we are closing all open PRs. Please re-open on https://github.com/NASA-IMPACT/veda-data if needed.

**Pull request closed without merging**
